# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jmc_main <- function(k, n1, p1, p2, maxl, p1a, maxiterations, point, yfile, cfile, mfile, trace) {
    .Call(`_JMcmprsk_jmc_main`, k, n1, p1, p2, maxl, p1a, maxiterations, point, yfile, cfile, mfile, trace)
}

jmo_main <- function(k, n1, p1, p2, p1a, bq, K_num, j_max, point, betas, thetas, maxiterations, yfile, cfile, mfile, trace) {
    .Call(`_JMcmprsk_jmo_main`, k, n1, p1, p2, p1a, bq, K_num, j_max, point, betas, thetas, maxiterations, yfile, cfile, mfile, trace)
}

SimDataC <- function(k_val, p1_val, p2_val, g_val, yfn, cfn, mfn) {
    invisible(.Call(`_JMcmprsk_SimDataC`, k_val, p1_val, p2_val, g_val, yfn, cfn, mfn))
}

SimDataO <- function(k_val, p1_val, p2_val, g_val, yfn, cfn, mfn) {
    invisible(.Call(`_JMcmprsk_SimDataO`, k_val, p1_val, p2_val, g_val, yfn, cfn, mfn))
}

